# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29dbfbcf412d4b41b6110f963e302e7dbc7a62c1435589cce68a4a19fb3070f3bc1b5cc78bba1acda3ca429c90e0d05af6a86b9026b465c827ee2a2f0419c1b8

test:
  secret_key_base: 11ef1bb88fa14df55be12e27c2d1c73b72400ffbd2df28719b0b3d7880cd5fe176b49e8d9f39570fc7b1e0a927a625897380fbcb954cc62650a4a80a768fe128

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
